### ISSUE TITLE
Entrevista_Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo_judith#4]
[INFORME DE ENTREVISTA .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo_judith/files/9491964/INFORME.DE.ENTREVISTA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
